######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 5 20:58:26 2016
######################################################################

TEMPLATE = app
TARGET = bin/LevelEditor
DEPENDPATH += .
INCLUDEPATH += .

# Input
QT += widgets
OBJECTS_DIR = bin/
MOC_DIR = bin/
UI_DIR = src/ui/
HEADERS += src/LevelEditor.h
FORMS += forms/LevelEditor.ui
SOURCES += src/LevelEditor.cpp src/main.cpp
